name: Deploy Code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Delete previous run
        run: |
          kill $(pgrep python3)

      - name: Update code
        uses: actions/checkout@v3

  
      - name: Run application
        run: |
          cd /root/FredderLoop
          nohup python3 testBot.py &
          
