name: Deploy Code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Update code
        uses: actions/checkout@v3
  
      - name: Run application
        run: |
          git pull origin main
          cd /root/FredderLoop
          
          RUNNER_TRACKING_ID=""  # prevents cleanup of child processses
          nohup python3 testBot.py &
          
