name: Deploy Code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update code
        uses: actions/checkout@v3

      - name: Run application
        run: |
          cd /root/FredderLoop
          git pull origin main
          crontab /root/FredderLoop/cronjobs
