name: Deploy Code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update code
        uses: actions/checkout@v3
  
      - name: Run application
        run: |
          cd /root/actions-runner/_work/FredderLoop/FredderLoop
          git pull origin main
          RUNNER_TRACKING_ID=""  # prevents cleanup of child processses
          ./run
          
